export const channel = {
  SYNC_REQUEST: "SYNC_REQUEST",
  SYNC_BLOCK: "SYNC_BLOCK",
  SYNC_TRXN_REQUEST: "SYNC_TRXN_REQUEST",
  SYNC_TRXN: "SYNC_TRXN",
  CREATED_TRANSACTION: "CREATED_TRANSACTION",
  CREATED_BLOCK: "CREATED_BLOCK",
};
